location               = "Central India"
app_location           = "Southeast Asia"
resource_group_name    = "rg-allen-uc3"
app_service_plan_name  = "asp-allen-uc3"
frontend_app_name      = "allen-uc3-frontend-app"
backend_app_name       = "allen-uc3-backend-api"
storage_account_name   = "allenuc3appstor"
storage_container_name = "uploads"